### ISSUE TITLE
Suggestion: Extend topics to have a topic / sub-topic tree

### ISSUE THREAD

**Issue by connecteev** [austintoddj/canvas#519] opened 2019-06-20 17:14 UTC
I know we have since added 'topics' to cnvs based on this ticket
https://github.com/cnvs/canvas/issues/434

But I think topics could greatly benefit from having a tree structure with topics/sub-topics (of course, those that don't need to make use of that functionality wont!) but for a lot of content sites, this would be useful to have. For example, see these URLs:

https://www.huffpost.com/news/politics
https://www.huffpost.com/entertainment/comedy
You could have several sub-topics under 'news', like 'world', 'US', 'financial', 'politics' etc. Same applies to entertainment and other topics/sub-topics.

As mentioned earlier, with tags you dont have a hierarchy, with topics you do...and topics give you a lot of flexibility and allow the user to browse content by looking through the topic/subtopic tree - which can be presented in a multitude of ways, in menus, in sidebars, etc). Topics can also be shown in URLs like my.blog/travel/international/trip-to-cyprus, or: my.blog/recipes/easybake/my-favorite-soup, where travel and recipes are category slugs.

As far as back-end admin of topics and sub-topics, it could look like how wordpress does it here: https://prnt.sc/m4jnjs
(I'm not a huge fan of wordpress but this is one feature they do well on)

@austintoddj  I hope this sufficiently explains the background behind the ask, and I hope this feature will make it into cnvs, which imo is the best laravel cms at the moment!

**Comment by austintoddj** [comment] 2019-06-20 20:49
Not a bad idea. I'll keep this in mind as I work through the backlog of tasks that I want to get done here and update this if it makes it into a future release. 

Thanks for the suggestion!

**Comment by connecteev** [comment] 2019-06-20 22:00
Thanks Todd, and this is why I like Cnvs as much as I do! Look forward to seeing this idea come to fruition.

**Comment by austintoddj** [comment] 2020-02-18 15:13
At this time, I'm comfortable with the simple tags/topics structure that Canvas has and what it allows users to organize content by. 

Good suggestion though, keep 'em coming!

**Comment by itsmysterybox** [comment] 2020-03-11 05:58
Does Canvas provide relationship between topics and tags? I am trying to implement a mega menu like [Cloudways blog](https://www.cloudways.com/blog/). I want to grab the tags related to the topics from the database dynamically. Does Canvas provides such relationship?

Dropdown under **Apps** may be a little complex to implement with topics, sub-topics and tags.

![Screenshot_1](https://user-images.githubusercontent.com/43930682/76386041-5838ac80-6389-11ea-8b86-fd2acbfcfb26.png)

But as you want to keep simple tags/topics structure, it will be good to have some relationship to implement such a simple dropdown.

![Screenshot_2](https://user-images.githubusercontent.com/43930682/76385895-f37d5200-6388-11ea-877f-4fae562dae4b.png)

**Comment by austintoddj** [comment] 2020-03-11 10:24
@itsmysterybox There isn't currently a relationship between the two. I'll re-open this and see if I can get something like this in a future release.

**Comment by austintoddj** [comment] 2020-09-28 13:29
Closing this because I don't see enough use-cases to build relationships between tags/topics. They work as intended. If you feel differently, feel free to let me know.

**Closed by austintoddj** 2020-09-28 13:29 UTC
Labels: enhancement
