### ISSUE TITLE
404 errors in api requests and path issue

### ISSUE THREAD

**Issue by asne11** [austintoddj/canvas#790] opened 2020-08-03 03:06 UTC
![Screenshot_104](https://user-images.githubusercontent.com/69129049/89142021-e34a5700-d563-11ea-8276-3717d79a7eda.png)

Issue is path! the path should be **http://localhost/test/git_clone/public/canvas** but instead path is **http://localhost/cavas**  can't seem to find what's the issue! at first I thought there's issue with laravel-mix so tried changing mix to asset and moving css and js files to public but then also when i go to this url **http://localhost/test/git_clone/public/canvas** it redirect me to **http://localhost/cavas**  but interestingly assets get loaded fine but then api starts showing 404 error which totally obvious but laravel is installed in htdocs/test/git_clone folder not in htdocs folder (i.e. root folder)! any one faced similar issue? or did I missed anything?

**Comment by austintoddj** [comment] 2020-08-03 14:22
What are you trying to run or host this with?

**Comment by asne11** [comment] 2020-08-04 09:07
xampp

**Comment by asne11** [comment] 2020-08-04 09:08
also m using laravel 7! is it not compatible with laravel 7?

**Comment by austintoddj** [comment] 2020-08-04 13:13
It is compatible with Laravel 7. So based on your first comment, are you seeing the assets load, but not the api calls? Or simply nothing at all?

**Comment by asne11** [comment] 2020-08-04 14:36
nothing at all! i tried providing actual path to app.js and app.css but then api 404 error started appearing and that url localhost/canvas opens ! instead it should have opened localhost/test/git_clone/public/canvas!!

**Comment by austintoddj** [comment] 2020-08-04 17:12
And just to verify, you did follow all the [installation steps](https://github.com/cnvs/canvas#installation) and it installed successfully?

**Comment by asne11** [comment] 2020-08-05 02:39
yp! 
3steps
-- composer require cnvs/canvas
--php artisan canvas:install
--php artisan storage:link

is there anything else i should have done?

**Comment by asne11** [comment] 2020-08-05 02:40
also tried php artisan canvas:publish --force (read it one of the issue forums)

**Comment by austintoddj** [comment] 2020-08-05 17:21
Nope those are the only steps you'd need. Let me dig into this a bit more and see if I can see what's going on.

**Comment by asne11** [comment] 2020-08-06 09:45
ok!

**Comment by austintoddj** [comment] 2020-08-07 15:10
Still unable to reproduce this. I'll post back here when I figure out more.

**Comment by asne11** [comment] 2020-08-08 03:26
ok! will be waiting!

**Comment by austintoddj** [comment] 2020-09-14 16:43
@asne11 Have you had this particular issue with the latest version?

**Comment by asne11** [comment] 2020-09-14 19:41
haven't tried it yet!

**Comment by austintoddj** [comment] 2020-10-02 11:47
Closing this out since it's been 3 weeks with no further information. If the problem still exists, let me know.

**Closed by austintoddj** 2020-10-02 11:47 UTC
Labels: needs more info
