### ISSUE TITLE
Cannot start up my applciation Error when login in

### ISSUE THREAD

**Issue by kevinwaxi** [austintoddj/canvas#1036] opened 2022-04-08 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Call to undefined method Canvas\Models\User::authentications() - The main error that i am getting.
Currently, i am using laravel sail/docker with laravel 9. Users seemed to be seeded but I can not get past this error

**Comment by austintoddj** [comment] 2022-04-08 18:56
Could you add a stack trace?

**Comment by jbenavidesv87** [comment] 2022-04-09 11:11
I can help with this one:
`Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update 'sessions' set 'payload'`

**Comment by austintoddj** [comment] 2022-04-09 23:55
Marked as a duplicate of #851

**Closed by austintoddj** 2022-04-09 23:55 UTC
Labels: bug, needs more info
