### ISSUE TITLE
Error installing canvas:ui

### ISSUE THREAD

**Issue by jvallef** [austintoddj/canvas#918] opened 2021-01-18 17:03 UTC
Hi

Base Canvas installation with Laravel 8 works ok, but trying to install canvas:ui, when run "npm run dev" got following error:

`npm run dev

> dev
> npm run development

> development
> mix

sh: mix: command not found
npm ERR! code 127
npm ERR! path /Users/xxx/web/canvascms
npm ERR! command failed
npm ERR! command sh -c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-01-18T16_46_50_689Z-debug.log
npm ERR! code 127
npm ERR! path /Users/xxx/web/canvascms
npm ERR! command failed
npm ERR! command sh -c npm run development

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-01-18T16_46_50_738Z-debug.log`

This is the content of debug.log
`0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.4.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/xxx/web/canvascms/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/xxx/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 12ms
19 verbose npm-session 0d37ad9ef590a26d
20 timing npm:load Completed in 24ms
21 timing command:run-script Completed in 573ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd /Users/xxx/web/canvascms
24 verbose Darwin 17.7.0
25 verbose argv "/usr/local/Cellar/node/15.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
26 verbose node v15.4.0
27 verbose npm  v7.0.15
28 error code 127
29 error path /Users/xxx/web/canvascms
30 error command failed
31 error command sh -c npm run development
32 verbose exit 127
`
As you asked in other issue about package.json and resolve-url-loader, this is the content...
`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.21.1",
        "bootstrap": "^4.5.3",
        "cross-env": "^7.0.3",
        "highlight.js": "^10.5.0",
        "jquery": "^3.5.1",
        "laravel-mix": "^5.0.7",
        "lodash": "^4.17.20",
        "medium-zoom": "^1.0.6",
        "moment": "^2.29.1",
        "nprogress": "^0.2.0",
        "popper.js": "^1.16.1",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.32.0",
        "sass-loader": "^10.1.0",
        "vue": "^2.6.12",
        "vue-infinite-loading": "^2.4.5",
        "vue-meta": "^2.4.0",
        "vue-router": "^3.4.9",
        "vue-template-compiler": "^2.6.12"
    }
}
`
Thanks in advance for your support

**Comment by jvallef** [comment] 2021-01-18 17:07
Sorry for formatting, looks like an issue with Git's editor. Let me copy and paste with no format

Displayed error...
npm run dev

> dev
> npm run development


> development
> mix

sh: mix: command not found
npm ERR! code 127
npm ERR! path /Users/jvallefdz/web/canvascms
npm ERR! command failed
npm ERR! command sh -c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jvallefdz/.npm/_logs/2021-01-18T16_46_50_689Z-debug.log
npm ERR! code 127
npm ERR! path /Users/jvallefdz/web/canvascms
npm ERR! command failed
npm ERR! command sh -c npm run development

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jvallefdz/.npm/_logs/2021-01-18T16_46_50_738Z-debug.log

debug.log...
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.4.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/xxx/web/canvascms/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/xxx/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 12ms
19 verbose npm-session 0d37ad9ef590a26d
20 timing npm:load Completed in 24ms
21 timing command:run-script Completed in 573ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd /Users/xxx/web/canvascms
24 verbose Darwin 17.7.0
25 verbose argv "/usr/local/Cellar/node/15.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
26 verbose node v15.4.0
27 verbose npm  v7.0.15
28 error code 127
29 error path /Users/xxx/web/canvascms
30 error command failed
31 error command sh -c npm run development
32 verbose exit 127


package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.21.1",
        "bootstrap": "^4.5.3",
        "cross-env": "^7.0.3",
        "highlight.js": "^10.5.0",
        "jquery": "^3.5.1",
        "laravel-mix": "^5.0.7",
        "lodash": "^4.17.20",
        "medium-zoom": "^1.0.6",
        "moment": "^2.29.1",
        "nprogress": "^0.2.0",
        "popper.js": "^1.16.1",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.32.0",
        "sass-loader": "^10.1.0",
        "vue": "^2.6.12",
        "vue-infinite-loading": "^2.4.5",
        "vue-meta": "^2.4.0",
        "vue-router": "^3.4.9",
        "vue-template-compiler": "^2.6.12"
    }
}

**Comment by austintoddj** [comment] 2021-01-18 19:39
What version of Laravel are you using?

**Comment by makhweb** [comment] 2021-01-19 02:17
The same error

**Comment by austintoddj** [comment] 2021-01-19 03:03
Duplicate of #916 

There's some troubleshooting [steps listed here](https://github.com/austintoddj/canvas/issues/916#issuecomment-761593699).

If you guys can think of any solutions, go ahead and drop them on that issue and I'll be more than happy to make adjustments.

**Closed by austintoddj** 2021-01-19 03:03 UTC
